ALTER TABLE rhiza_projects
  ADD COLUMN state jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE rhiza_nodes
  ADD COLUMN source_message_id uuid REFERENCES rhiza_messages(id) ON DELETE SET NULL,
  ADD COLUMN anchor_text text;

ALTER TABLE rhiza_messages
  ADD COLUMN event_ordinal bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE rhiza_messages
  ADD CONSTRAINT rhiza_messages_node_event_ordinal_key UNIQUE (node_id, event_ordinal);

CREATE TABLE rhiza_audit_events (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES rhiza_projects(id) ON DELETE CASCADE,
  node_id uuid REFERENCES rhiza_nodes(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (char_length(action) BETWEEN 1 AND 120),
  entity_type text NOT NULL CHECK (entity_type IN ('project', 'node', 'segment', 'event', 'workspace')),
  entity_id uuid NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX rhiza_nodes_source_node_idx ON rhiza_nodes(source_node_id) WHERE source_node_id IS NOT NULL;
CREATE INDEX rhiza_nodes_source_message_idx ON rhiza_nodes(source_message_id) WHERE source_message_id IS NOT NULL;
CREATE INDEX rhiza_segments_node_idx ON rhiza_segments(node_id, ordinal);
CREATE INDEX rhiza_messages_segment_idx ON rhiza_messages(segment_id) WHERE segment_id IS NOT NULL;
CREATE INDEX rhiza_messages_source_idx ON rhiza_messages(source_message_id) WHERE source_message_id IS NOT NULL;
CREATE INDEX rhiza_messages_reply_idx ON rhiza_messages(reply_to_message_id) WHERE reply_to_message_id IS NOT NULL;
CREATE INDEX rhiza_edges_source_idx ON rhiza_edges(source_node_id);
CREATE INDEX rhiza_edges_target_idx ON rhiza_edges(target_node_id);
CREATE INDEX rhiza_anchors_node_idx ON rhiza_anchors(node_id);
CREATE INDEX rhiza_message_attachments_attachment_idx ON rhiza_message_attachments(attachment_id);
CREATE INDEX rhiza_audit_project_idx ON rhiza_audit_events(project_id, created_at DESC);
CREATE INDEX rhiza_audit_node_idx ON rhiza_audit_events(node_id, created_at DESC) WHERE node_id IS NOT NULL;
